### PR TITLE
Ported shaders from three.js/examples/js/shaders 

### PR DESCRIPTION
**Pull request by cgrabowski**
Ported shaders from three.js/examples/js/shaders to three.dart/lib/extras/shaders as three_shaders library as part of my greater goal of porting over the postprocessing code from three.js/examples/js/postprocessing. (Some of these shaders are used by the postprocessing code.)

### CODE REVIEW

**Comment by johsin18** [comment]
You could have used the Dart triple double quote notation for multiline strings and/or the fact that consecutive strings are automatically concateanted `String s ="""a""" """b""";`, but I guess it was easier porting (and maintaining) using `.join("\n")`

**Comment by cgrabowski** [comment]
I used grep and sed to port the files in about an hour. Once the files where valid and seemingly useful, dynamic Dart (and through no deliberate intent still valid JavaScript) I stopped. I was hesitant to make any further changes without a clear reason.

I ported the postprocessing code today and am in the middle of getting it to work. In the process I did come up with an idea that these shaders could be left dynamic but accompanied by a ShaderProgram class that produces typed shaders from the dynamic ones. (Could they be somehow inter-operable?)

Here is the gist for the ShaderProgram class I am using in my postprocessing port: https://gist.github.com/71f9ca3ccd4ba1fef1d4.git

**Comment by nelsonsilva** [comment]
@cgrabowski Thank you!
Would be cool to merge the post processing stuff before the next release. Any ETA on that?

**Comment by cgrabowski** [comment]
ETA is unclear, but my I think it could be done within a week. I ported all the code over, and it has no errors or warnings. I am currently porting the examples over.

I noticed this will require at least a change to the WebGLRenderer.render function signature. So, with that in mind I think I should open an issue. I will push everything I've done so far to my postprocessing branch (after merging it with master) and link to the branch in the issue so anyone can help with it.

**Pull request merged**
