### PR TITLE
Add MTLLoader and MTL support in the OBJLoader

### PR DESCRIPTION
**Pull request by seguins**

### CODE REVIEW

**Comment by johsin18** [comment]
For a proper review, I would prefer to have the bug fix commit and the added example code squashed into a single commit with the main addition. Conversely, factorize out the changes to existing code into a separate commit (with an explanation why it had to be done), i.e. the changes on web_gl_loader_obj.dart and obj_loader.dart.

**Comment by johsin18** [comment]
I have tested both web_gl_loader_obj.html and web_gl_loader_obj_mtl.html in Dartium and Firefox.  Only problem is that I cannot rotate etc. when compiled to JavaScript, but this seems unrelated to the patch.

**Comment by nelsonsilva** [comment]
Not sure how to properly merge this as you have two new features and a single commit fixing issues in both. Should I squash these or cherry pick each one + amend with relevant fixes ? @johsin18 @seguins

**Comment by seguins** [comment]
I hadn't tested on the javascript version. I'm looking for the bug, and it seems it's a bug about the event management. I have fixed the problem, so I will integrate it in the next commit.

The OBJLoader is now linked with MTLLoader, so I think I can do a single commit for all changes ? And in the commit's message I explain the difference in the public interface of OBJLoader.

**Comment by johsin18** [comment]
Single commit with comment sounds good to me.

**Comment by seguins** [comment]
This PR is replaced by #167

**Pull request closed without merging**
