### PR TITLE
dartfmt: issue #166

### PR DESCRIPTION
**Pull request by beatgammit**
This touches nearly every file, so please do not merge if there are outstanding pull-requests, as nothing will merge cleanly.

This pull-request is merely the result of:

    dartfmt -l 120 -w lib example tool

If briefly reviewed the changes and they seem to mostly be non-destructive. I'm working on a contributer's guide, so let me know if you'd like that included in this pull-request.

Once this is merged, I'll probably start working on making the codebase more idiomatic Dart.

### CODE REVIEW

**Comment by beatgammit** [comment]
@nelsonsilva - Sorry it took so long. The PR has been updated.

**Comment by nelsonsilva** [comment]
Thanks @beatgammit I amended your commit with a few more changes I got after running dartfmt locally.
I've merged and pushed this and will try to get the "-t" (code transformation) going as well.

**Comment by nelsonsilva** [comment]
@beatgammit I ended up reverting the dartfmt changes for shaders since we rely on manual indentation to keep shaders readable.
I also added a tool/dartfmt.sh to apply dartfmt but skip shaders.

**Comment by beatgammit** [comment]
Awesome!

**Pull request closed without merging**
